name: Docker Build Image CI

on:
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build DB docker image
        working-directory: Database
        run: docker build -t localmysql:v1 .

      - name: Build Frontend Image
        working-directory: Frontend\InsuranceBrokerWebapp
        run: docker build -t InsuranceBrokerWebapp:v1 .

      - name: Build Backend Image
        working-directory: Backend\WebApi
        run: docker build -t Webapi:v1 .
